// vue-native-vn/src/screens/About.vue
<template>
  <view class="container">
    <view>
      <text>About Various News - vue-native version<text>
    </view>
    <text>By: tamatamvan</Text>
  </view>
</template>


<style>
 .container {
   flex: 1;
   justify-content: center;
   align-items: center;
   flex-direction: column;
 }
</style>

// react-native-vn/screens/About.js
import React, { Component } from 'react';
import { View, Text, StyleSheet} from 'react-native';

class About extends Component {
  static navigationOptions = {
    title: 'About - Various News'
  }
  render() {
    return (
      <View style={ styles.container }>
        <Text>Various News - React Native Version</Text>
        <Text>By: tamatamvan</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1, 
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default About;
