// react-native-vn/src/components/NewsList.js
import React, { Component } from 'react';
import {
  FlatList,
  Alert
} from 'react-native';

import NewsCard from './NewsCard';

import { API_KEY } from '../../config';

import axios from 'axios';

class NewsList extends Component {
  state = {
    articles: [],
  }

  loadArticles = () => {
    axios.get(`https://newsapi.org/v2/top-headlines?sources=techcrunch&apiKey=${API_KEY}`)
      .then(({data}) => {
        this.setState({
          articles: data.articles,
        });
      })
      .catch(err => {
        Alert.alert('Failed to fetch news!');
      });
  }

  renderItem = ({ item }) => <NewsCard article = { item }/>

  keyExtractor = (item, idx) => `news-${item.source.id}-${idx}`

  componentDidMount() {
    this.loadArticles();
  }

  render() {
    return (
      <FlatList 
        data = { this.state.articles }
        renderItem = { this.renderItem }
        keyExtractor = { this.keyExtractor } 
      />
    );
  }
}


export default NewsList;

// vue-native-vn/src/components/NewsList.vue
<template>
  <flat-list 
    :data="articles"
    :render-item="({item}) => renderListItem(item)"
    :key-extractor="(item, idx) => `article-${item.source.id}-${idx}`"
  />
</template>

<script>
import React from 'react';
import axios from 'axios';

import NewsCard from './NewsCard.vue';

import { Alert } from 'react-native';
import { API_KEY } from '../../config.js';

export default {
  data () {
    return {
      articles: [],
    }
  },
  methods: {
    fetchNews () {
      axios.get(`https://newsapi.org/v2/top-headlines?sources=techcrunch&apiKey=${API_KEY}`)
        .then(({data}) => {
          this.articles = data.articles;
        })
        .catch(() => Alert.alert('Failed to fetch data!'));
    },
    renderListItem (item) {
      return (<NewsCard article={ item }/>)
    },
  },
  mounted () {
    this.fetchNews();
  },
}
</script>
