// react-native-vn/src/components/NewsCard.js
import React, { Component } from 'react';
import {
  View,
  Text,
  Image,
  TouchableOpacity,
  Linking,
  StyleSheet,
} from 'react-native';

const NewsCard = ({ article }) => (
  <View style={ styles.container }> 
    <Image 
      style={ styles.image }
      source={{ uri: article.urlToImage }}
    />
    <Text style={ styles.title }>{ article.title }</Text>
    <TouchableOpacity style={ styles.readMoreBtn }
      onPress={ () => Linking.openURL(article.url) }
    >
      <Text style={ styles.readMoreTxt }>Read More</Text>
    </TouchableOpacity>
  </View>
)

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    marginBottom: 8,
    elevation: 2,
  },
  image: { 
    width: '100%', 
    height: 200, 
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    padding: 4,
  },
  readMoreBtn: {
    backgroundColor: '#2962FF',
    padding: 8,
  },
  readMoreTxt: {
    color: '#fff',
    textAlign: 'center',
  },
});

export default NewsCard;

// vue-native-vn/src/components/NewsCard.vue
<template>
  <view class="card-outer">
    <image
      :source="{ uri: article.urlToImage }"
      :style="{ width: '100%', height: 200 }"
    />
    <text class="card-title">{{ article.title }}</text>
    <touchable-opacity class="card-button" :on-press="openLink">
      <text class="card-button-txt">Read More</text>
    </touchable-opacity>
  </view>
</template>

<script>
import { Linking } from 'react-native';

export default {
  props: [ 'article' ],
  methods: {
    openLink () {
      Linking.openURL(this.article.url);
    },
  },
}
</script>


<style>
.card-outer {
  background-color: #fff;
  margin-bottom: 8;
  elevation: 2;
}
.card-title {
  font-size: 18;
  font-weight: bold;
  padding: 4;
}
.card-button {
  padding: 8;
  background-color: #2962ff;
}
.card-button-txt {
  color: #fff;
  text-align: center;
}
</style>
