// vue-native-vn/components/NewsCard.vue
<template>
  <view class="card-outer">
    <image
      :source="{ uri: article.urlToImage }"
      :style="{ width: '100%', height: 200 }"
    />
    <text class="card-title">{{ article.title }}</text>
  </view>
</template>

<script>
export default {
  props: [ 'article' ]
}
</script>


<style>
.card-outer {
  background-color: #fff;
  margin-bottom: 8;
  elevation: 2;
}
.card-title {
  font-size: 18;
  font-weight: bold;
  padding: 4;
}
</style>

// react-native-vn/components/NewsCard.js
import React, { Component } from 'react';
import {
  View,
  Text,
  Image,
  StyleSheet,
} from 'react-native';

const NewsCard = ({ article }) => (
  <View style={ styles.container }> 
    <Image 
      style={ styles.image }
      source={{ uri: article.urlToImage }}
    />
    <Text style={ styles.title }>{ article.title }</Text>
  </View>
)

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    marginBottom: 8,
    elevation: 2,
  },
  image: { 
    width: '100%', 
    height: 200, 
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    padding: 4,
  },
});

export default NewsCard;
