// vue-native-vn/App.vue
<template>
  <app-navigation/>
</template>

<script>
import React from 'react';
import { Text } from 'react-native';
// import { MaterialIcons } from '@expo/vector-icons';

import { StackNavigator } from 'vue-native-router';

import HomeScreen from './src/screens/Home.vue';
import AboutScreen from './src/screens/About';

const AppNavigation = StackNavigator({
  Home: {
    screen: HomeScreen,
    navigationOptions: ({ navigation }) => ({
      title: 'Home - Various News',
      headerRight: (
        <Text 
          onPress={ () => navigation.navigate("About") }
          style={{
            padding: 16,
            color: '#fff',
          }}
        >
          About
        </Text>
      ) 
    }),
  },
  About: {
    screen: AboutScreen,
    navigationOptions: {
      title: 'About',
    },
  },
}, {
  initialRouteName: 'Home',
  navigationOptions: {
    headerStyle: {
      backgroundColor: '#2962ff',
    },
    headerTintColor: '#fff',
  },
});

export default {
  components: {
    AppNavigation
  }
}
</script>

 
<style>
.container {
  background-color: white;
  align-items: center;
  justify-content: center;
  flex: 1;
}
.text-color-primary {
  color: blue;
}
</style>

// react-native-vn/App.js
import React from 'react';
import { Text, View } from 'react-native';

import Home from './src/screens/Home';
import About from './src/screens/About';

import { createStackNavigator } from 'react-navigation';

const RootStack = createStackNavigator({
  Home: {
    screen: Home,
  },
  About: {
    screen: About,
  },
}, {
  initialRouteName: 'Home',
  navigationOptions: {
    headerStyle: {
      backgroundColor: '#2962FF',
    },
    headerTintColor: '#fff',
  },
});

export default class App extends React.Component {
  render() {
    return (
      <RootStack/>
    );
  }
}
